-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 16:51:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aroma_coffee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aroma_coffee` ;

-- -----------------------------------------------------
-- Schema aroma_coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aroma_coffee` ;
USE `aroma_coffee` ;

-- -----------------------------------------------------
-- Table `aroma_coffee`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aroma_coffee`.`user` ;

CREATE TABLE IF NOT EXISTS `aroma_coffee`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(120) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `role` ENUM("customer", "seller") NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aroma_coffee`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aroma_coffee`.`product` ;

CREATE TABLE IF NOT EXISTS `aroma_coffee`.`product` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `stock` SMALLINT UNSIGNED NOT NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `products_UNIQUE` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `product_type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aroma_coffee`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aroma_coffee`.`order` ;

CREATE TABLE IF NOT EXISTS `aroma_coffee`.`order` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `take_away` BIT NOT NULL,
  PRIMARY KEY (`order_id`, `user_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_customer_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`user_id`)
    REFERENCES `aroma_coffee`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aroma_coffee`.`order_has_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aroma_coffee`.`order_has_product` ;

CREATE TABLE IF NOT EXISTS `aroma_coffee`.`order_has_product` (
  `order_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `user_id`, `product_id`),
  INDEX `fk_order_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id` , `user_id`)
    REFERENCES `aroma_coffee`.`order` (`order_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `aroma_coffee`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
